CREATE TABLE IF NOT EXISTS story (
  id INTEGER NOT NULL,
  datetime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  text TEXT NOT NULL,

  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS keyword (
  story_id INTEGER NOT NULL,
  text TEXT NOT NULL,
  CONSTRAINT keywords
    FOREIGN KEY (story_id)
    REFERENCES story(id)
    ON DELETE CASCADE
);

